base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data_given/winequality.csv

load_data:
  raw_dataset_csv: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/raw/winequality.csv

split_data:
  train_path: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/processed/train_winequality.csv
  test_path: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
#       alpha: 0.88
#       l1_ratio: 0.89
#       alpha: 0.9
#       l1_ratio: 0.4
       alpha: 0.6
       l1_ratio: 0.24

model_dir: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/saved_models

reports:
  params: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/report/params.json
  scores: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/report/scores.json

webapp_model_dir: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/prediction_services/updated_model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: wineq_Elastinet_regression
  run_name: mlops
  registered_model_name: ElasticNetModel
  remote_server_uri: http://0.0.0.0:1234