base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data_given/winequality.csv

load_data:
  raw_dataset_csv: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/raw/winequality.csv

split_data:
  train_path: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/processed/train_winequality.csv
  test_path: /home/scaledge-riya/Desktop/MLops_demo_projects/wine_predicton_DVC/data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
       alpha: 0.88
       l1_ratio: 0.89

model_dir: saved_models

#reports:
#  params: report/params.json
#  scores: report/scores.json
#
#webapp_model_dir: prediction_service/model/model.joblib